### ISSUE TITLE
Where to edit main page

### ISSUE THREAD

**Issue by MFracassoSFA** [SwissFederalArchives/lindas-admin-ch#36]
Hello @ludovicm67 
I hope you've had great holidays :)

I just have a small question and was wondering, where I can edit the mainpage https://lindas.admin.ch/ ?

Best regards
Mario

**Comment by ludovicm67** [comment]
Hi @MFracassoSFA 

Yes, it was great to have some days off! :)

To update the homepage, it's happening here:
- the template part: `views/welcome.hbs`
- to edit what will be displayed instead of `{{{ session.markdown-content-plugin.lindas.about-lindas }}}`, you will need to edit the files here: `content/template-parts/about-lindas/`
- same for `{{{ session.markdown-content-plugin.lindas.linked-data }}}`, you will need to edit the files in `content/template-parts/linked-data/`

It's not the same thing as the other pages, as previously we had the need to display the content in two columns, display a YouTube video that is different depending on the language, and so on.

Feel free to update what is relevant for your needs.

Best,
Ludovic.

**Comment by MFracassoSFA** [comment]
Hello @ludovicm67 

Nice to hear! :)

Ah, great thank you so much for  the detailled description, it worked perfectly fine. I understand why it was done like that!

I'll merge now.

Thank you very much and have a wonderful day.
Mario
